version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlgoB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdev
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
