server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbname: shopdev
  max_idle_conns: 100
  log_mode: true
  conMaxLifetime: 3600
logger:
  level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password: 
  database: 0